# Local configuration
local:
  JWT_SECRET_KEY: "local_secret_key_here"
  PORT: "8080"
  CORS_ALLOWED_ORIGIN: "*"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_NAME: "flashcards_db"
  DB_USER: "local_user"
  DB_PASSWORD: "local_password"
  SERVER_PORT: "8080"
  LOG_LEVEL: "debug"

# Production configuration
production:
  JWT_SECRET_KEY: "prod_secret_key_here"
  PORT: "8080"
  CORS_ALLOWED_ORIGIN: "https://lobster-app-jgtjk.ondigitalocean.app"
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
