name: Deploy

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        cd backend
        go build -o main ./cmd/main.go

    - name: Deploy to server
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        mkdir -p ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        
        # Stop the running service
        echo "Stopping the running service"
        ssh -i private_key -o "IdentitiesOnly=yes" $USER@$HOST "sudo systemctl stop flash-cards.service"
        
        # Copy the binary to the server
        echo "Copying the binary to the server"
        scp -i private_key backend/main $USER@$HOST:/go-web/flash-cards/backend
        
        # Set appropriate permissions
        echo "Setting appropriate permissions"
        ssh -i private_key -o "IdentitiesOnly=yes" $USER@$HOST "chmod +x /go-web/flash-cards/backend/main"
        
        # Reload the service
        echo "Reloading the service"
        ssh -i private_key -o "IdentitiesOnly=yes" $USER@$HOST "sudo systemctl daemon-reload"

        # Clean up
        rm -f private_key