name: Deploy

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        cd backend
        go build -o main ./cmd/main.go

    - name: Deploy to server
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
        SUDO_PASSWORD: ${{ secrets.SERVER_SUDO_PASSWORD }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

        mkdir -p ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        
        # Copy the new executable to a temporary location
        ssh -i private_key -o "IdentitiesOnly=yes" $USER@$HOST "mkdir -p /go-web/flash-cards/backend/tmp"
        scp -i private_key -o "IdentitiesOnly=yes" backend/main $USER@$HOST:/go-web/flash-cards/backend/tmp/main-new
        
        # Perform the swap
        ssh -i private_key -o "IdentitiesOnly=yes" $USER@$HOST "
          echo '$SUDO_PASSWORD' | sudo -S service goweb stop
          mv /go-web/flash-cards/backend/main /go-web/flash-cards/backend/main-old
          mv /go-web/flash-cards/backend/tmp/main-new /go-web/flash-cards/backend/main
          chmod +x /go-web/flash-cards/backend/main
          echo '$SUDO_PASSWORD' | sudo -S service goweb start
        "

        # Clean up
        ssh -i private_key -o "IdentitiesOnly=yes" $USER@$HOST "rm -f /go-web/flash-cards/backend/main-old"
        rm -f private_key

    
