name: Deploy

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        cd backend
        go build -o main ./cmd/main.go

    - name: Deploy to server
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        mkdir -p ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        # Debug: Check the content of the private key (redacted)
        echo "Private key file contents (first line):"
        head -n 1 private_key
        
        # Debug: Verify SSH connection
        ssh -v -i private_key $USER@$HOST "echo 'SSH connection successful'"
        scp -i private_key backend/main $USER@$HOST:/go-web/flash-cards/backend/
        ssh -i private_key $USER@$HOST "systemctl daemon-reload"
        rm -f private_key